name: Go

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.1'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        go list -m github.com/vivekjha1213/go-secretsafe@v1.1.0
        # Additional steps can be added here if needed
      env:
        GOPROXY: proxy.golang.org
