name: Publish Go Module

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Build and test
      run: go test ./...

    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go list -m github.com/vivekjha1213/go-secretsafe@${{ github.ref_name }}
